"""Proofline public API."""

from .evaluation import (
    EvaluationResult,
    ExpectedTarget,
    RetrievalCase,
    RetrievalEvaluator,
    RetrievalSuite,
    load_retrieval_suite,
)
from .hashing import (
    artifact_id_from_sha256,
    evidence_id_from_locator,
    sha256_bytes,
    sha256_file,
    sha256_text,
    source_id_from_uri,
    stable_id,
)
from .ingest import IngestResult, Ingestor
from .models import (
    Artifact,
    EvidenceReference,
    EvidenceUnit,
    EvidenceUnitType,
    Lead,
    LeadStatus,
    Observation,
    ObservationStatus,
    ProcessingEvent,
    SourceReference,
)
from .ocr import OcrBackend, OcrPageResult, PyMuPDFTesseractBackend
from .progressive import ProgressiveExtractionResult, ProgressiveExtractor
from .review import (
    ReviewItem,
    extraction_attempts,
    preferred_extraction,
    review_count,
    review_queue,
)
from .search import IndexBuildResult, SearchHit, SearchIndex, normalize_lexical_query
from .storage import ProoflineStore
from .structured import (
    StructuredBuildResult,
    StructuredFact,
    StructuredHit,
    StructuredIndex,
    extract_structured_facts,
    parse_query_date,
)
from .watcher import (
    CorpusWatcher,
    ManifestResource,
    SourceManifest,
    WatchResult,
    WatchState,
    load_manifest,
    manifest_sequence_gaps,
)

__all__ = [
    "Artifact",
    "CorpusWatcher",
    "EvaluationResult",
    "EvidenceReference",
    "EvidenceUnit",
    "EvidenceUnitType",
    "ExpectedTarget",
    "IndexBuildResult",
    "IngestResult",
    "Ingestor",
    "Lead",
    "LeadStatus",
    "ManifestResource",
    "Observation",
    "ObservationStatus",
    "OcrBackend",
    "OcrPageResult",
    "ProcessingEvent",
    "ProgressiveExtractionResult",
    "ProgressiveExtractor",
    "ProoflineStore",
    "PyMuPDFTesseractBackend",
    "RetrievalCase",
    "RetrievalEvaluator",
    "RetrievalSuite",
    "ReviewItem",
    "SearchHit",
    "SearchIndex",
    "SourceManifest",
    "SourceReference",
    "StructuredBuildResult",
    "StructuredFact",
    "StructuredHit",
    "StructuredIndex",
    "WatchResult",
    "WatchState",
    "artifact_id_from_sha256",
    "evidence_id_from_locator",
    "extract_structured_facts",
    "extraction_attempts",
    "load_manifest",
    "load_retrieval_suite",
    "manifest_sequence_gaps",
    "normalize_lexical_query",
    "parse_query_date",
    "preferred_extraction",
    "review_count",
    "review_queue",
    "sha256_bytes",
    "sha256_file",
    "sha256_text",
    "source_id_from_uri",
    "stable_id",
]
