"""Proofline public API."""

from .candidate_analysis import (
    CandidateObservationItem,
    CandidateObservationRun,
    CandidateObservationRunner,
)
from .detectors.recurrence_variation import (
    RecurrenceVariationCandidate,
    RecurrenceVariationDecision,
    evaluate_recurrence_variation,
)
from .discovery import (
    DiscoveryPlan,
    DiscoveryResult,
    DiscoverySpec,
    SourceDiscoverer,
    discover_civicengage_resources,
    load_discovery_plan,
    manifest_to_dict,
)
from .evaluation import (
    EvaluationResult,
    ExpectedTarget,
    RetrievalCase,
    RetrievalEvaluator,
    RetrievalSuite,
    load_retrieval_suite,
)
from .families import SourceFamily, SourceFamilyResolver
from .hashing import (
    artifact_id_from_sha256,
    evidence_id_from_locator,
    sha256_bytes,
    sha256_file,
    sha256_text,
    source_id_from_uri,
    stable_id,
)
from .ingest import IngestResult, Ingestor
from .models import (
    Artifact,
    EvidenceReference,
    EvidenceUnit,
    EvidenceUnitType,
    Lead,
    LeadStatus,
    Observation,
    ObservationStatus,
    ProcessingEvent,
    SourceReference,
)
from .ocr import OcrBackend, OcrPageResult, PyMuPDFTesseractBackend
from .progressive import ProgressiveExtractionResult, ProgressiveExtractor
from .recurrence import (
    RecurrenceCluster,
    RecurrenceEdge,
    RecurrenceResult,
    SegmentRecurrenceClusterer,
)
from .recurrence_packets import (
    FactValue,
    RecurrenceEvidencePacket,
    RecurrenceEvidencePacketBuilder,
    RecurrenceOccurrencePacket,
    RecurrencePacketResult,
    SegmentFact,
)
from .review import (
    ReviewItem,
    extraction_attempts,
    preferred_extraction,
    review_count,
    review_queue,
)
from .search import IndexBuildResult, SearchHit, SearchIndex, normalize_lexical_query
from .segment_similarity import (
    NearDuplicateCandidate,
    NearDuplicateResult,
    SegmentOccurrence,
    SegmentSimilarityIndex,
    token_shingles,
)
from .segments import (
    EvidenceSegment,
    RepeatedSegmentGroup,
    SegmentBuildResult,
    SegmentHit,
    SegmentIndex,
    SegmentationPlan,
    SegmentationRule,
    load_segmentation_plan,
    segment_text,
    segmentation_plan_sha256,
)
from .storage import ProoflineStore
from .structured import (
    StructuredBuildResult,
    StructuredFact,
    StructuredHit,
    StructuredIndex,
    extract_structured_facts,
    parse_query_date,
)
from .watcher import (
    CorpusWatcher,
    ManifestResource,
    SourceManifest,
    WatchResult,
    WatchState,
    load_manifest,
    manifest_sequence_gaps,
)

__all__ = [
    "Artifact",
    "CandidateObservationItem",
    "CandidateObservationRun",
    "CandidateObservationRunner",
    "CorpusWatcher",
    "DiscoveryPlan",
    "DiscoveryResult",
    "DiscoverySpec",
    "EvaluationResult",
    "EvidenceReference",
    "EvidenceSegment",
    "EvidenceUnit",
    "EvidenceUnitType",
    "ExpectedTarget",
    "FactValue",
    "IndexBuildResult",
    "IngestResult",
    "Ingestor",
    "Lead",
    "LeadStatus",
    "ManifestResource",
    "NearDuplicateCandidate",
    "NearDuplicateResult",
    "Observation",
    "ObservationStatus",
    "OcrBackend",
    "OcrPageResult",
    "ProcessingEvent",
    "ProgressiveExtractionResult",
    "ProgressiveExtractor",
    "ProoflineStore",
    "PyMuPDFTesseractBackend",
    "RecurrenceCluster",
    "RecurrenceEdge",
    "RecurrenceEvidencePacket",
    "RecurrenceEvidencePacketBuilder",
    "RecurrenceOccurrencePacket",
    "RecurrencePacketResult",
    "RecurrenceResult",
    "RecurrenceVariationCandidate",
    "RecurrenceVariationDecision",
    "RepeatedSegmentGroup",
    "RetrievalCase",
    "RetrievalEvaluator",
    "RetrievalSuite",
    "ReviewItem",
    "SearchHit",
    "SearchIndex",
    "SegmentBuildResult",
    "SegmentFact",
    "SegmentHit",
    "SegmentIndex",
    "SegmentOccurrence",
    "SegmentRecurrenceClusterer",
    "SegmentSimilarityIndex",
    "SegmentationPlan",
    "SegmentationRule",
    "SourceDiscoverer",
    "SourceFamily",
    "SourceFamilyResolver",
    "SourceManifest",
    "SourceReference",
    "StructuredBuildResult",
    "StructuredFact",
    "StructuredHit",
    "StructuredIndex",
    "WatchResult",
    "WatchState",
    "artifact_id_from_sha256",
    "discover_civicengage_resources",
    "evidence_id_from_locator",
    "evaluate_recurrence_variation",
    "extract_structured_facts",
    "extraction_attempts",
    "load_discovery_plan",
    "load_manifest",
    "load_retrieval_suite",
    "load_segmentation_plan",
    "manifest_sequence_gaps",
    "manifest_to_dict",
    "normalize_lexical_query",
    "parse_query_date",
    "preferred_extraction",
    "review_count",
    "review_queue",
    "segment_text",
    "segmentation_plan_sha256",
    "sha256_bytes",
    "sha256_file",
    "sha256_text",
    "source_id_from_uri",
    "stable_id",
    "token_shingles",
]
